### ISSUE TITLE
Pattern match error when no arguments provided

### ISSUE THREAD

**Issue by glguy** [GaloisInc/grappa#1] opened 2018-09-05 16:06 UTC
Actual behavior:

```
$ stack exec grappa
grappa: user error (Pattern match failure in do expression at grappa/Main.hs:79:3-10)
```

Expected behavior:

grappa prints help or an error message when no arguments are provided!

**Comment by eddywestbrook** [comment] 2018-09-26 17:58
Duplicate of #2

**Closed by eddywestbrook** 2018-09-26 17:58 UTC
